package ro.vladutit.Don.t.forget.v2.model;

public enum Icon {
    Clock("fas fa-clock"),
    Ambulance("fas fa-ambulance"),
    Apple_alt("fas fa-apple-alt"),
    Baby("fas fa-baby"),
    Baby_carriage("fas fa-baby-carriage"),
    Barcode("fas fa-barcode"),
    Bath("fas fa-bath"),
    Beer("fas fa-beer"),
    Bell("fas fa-bell"),
    Bell_slash("fas fa-bell-slash"),
    Bible("fas fa-bible"),
    Biohazard("fas fa-biohazard"),
    Birthday_cake("fas fa-birthday-cake"),
    Brain("fas fa-brain"),
    Building("fas fa-building"),
    Bullhorn("fas fa-bullhorn"),
    Bus_alt("fas fa-bus-alt"),
    Business_time("fas fa-business-time"),
    Campground("fas fa-campground"),
    Car("fas fa-car"),
    Caravan("fas fa-caravan"),
    Car_crash("fas fa-car-crash"),
    Carrot("fas fa-carrot"),
    Cash_register("fas fa-cash-register"),
    Cat("fas fa-cat"),
    Certificate("fas fa-certificate"),
    Chair("fas fa-chair"),
    Charging_station("fas fa-charging-station"),
    Chess("fas fa-chess"),
    Church("fas fa-church"),
    Clinic_medical("fas fa-clinic-medical"),
    Cocktail("fas fa-cocktail"),
    Code("fas fa-code"),
    Code_branch("fas fa-code-branch"),
    Coffee("fas fa-coffee"),
    Comment("fas fa-comment"),
    Comment_alt("fas fa-comment-alt"),
    Concierge_bell("fas fa-concierge-bell"),
    Cookie_bite("fas fa-cookie-bite"),
    Couch("fas fa-couch"),
    Crow("fas fa-crow"),
    Crutch("fas fa-crutch"),
    Dice("fas fa-dice"),
    Dna("fas fa-dna"),
    Dog("fas fa-dog"),
    Dollar_sign("fas fa-dollar-sign"),
    Donate("fas fa-donate"),
    Drumstick_bite("fas fa-drumstick-bite"),
    Dumbbell("fas fa-dumbbell"),
    Egg("fas fa-egg"),
    Exclamation_triangle("fas fa-exclamation-triangle"),
    Faucet("fas fa-faucet"),
    Female("fas fa-female"),
    File_signature("fas fa-file-signature"),
    Fire_extinguisher("fas fa-fire-extinguisher"),
    Fish("fas fa-fish"),
    Football("fas fa-futbol"),
    Gas_pump("fas fa-gas-pump"),
    Gift("fas fa-gift"),
    Glasses("fas fa-glasses"),
    Graduation_cap("fas fa-graduation-cap"),
    Guitar("fas fa-guitar"),
    Hamburger("fas fa-hamburger"),
    Handshake("fas fa-handshake"),
    Heartbeat("fas fa-heartbeat"),
    Hiking("fas fa-hiking"),
    History("fas fa-history"),
    H_square("fas fa-h-square"),
    Ice_cream("fas fa-ice-cream"),
    Icicles("fas fa-icicles"),
    Key("fas fa-key"),
    Male("fas fa-male"),
    Map_marked_alt("fas fa-map-marked-alt"),
    Mobile_alt("fas fa-mobile-alt"),
    Music("fas fa-music"),
    Parking("fas fa-parking"),
    Piggy_bank("fas fa-piggy-bank"),
    Pizza_slice("fas fa-pizza-slice"),
    Pump_medical("fas fa-pump-medical"),
    Restroom("fas fa-restroom"),
    School("fas fa-school"),
    Seedling("fas fa-seedling"),
    Shipping_fast("fas fa-shipping-fast"),
    Smoking_ban("fas fa-smoking-ban"),
    Snowflake("fas fa-snowflake"),
    Snowman("fas fa-snowman"),
    Socks("fas fa-socks"),
    Spray_can("fas fa-spray-can"),
    Stamp("fas fa-stamp"),
    Syringe("fas fa-syringe"),
    Theater_masks("fas fa-theater-masks"),
    Thumbs_down("fas fa-thumbs-down"),
    Thumbs_up("fas fa-thumbs-up"),
    Toilet_paper("fas fa-toilet-paper"),
    Umbrella("fas fa-umbrella"),
    Umbrella_beach("fas fa-umbrella-beach"),
    User_graduate("fas fa-user-graduate"),
    User_md("fas fa-user-md"),
    Virus("fas fa-virus"),
    Wheelchair("fas fa-wheelchair"),
    Wind("fas fa-wind"),
    Wrench("fas fa-wrench");

    private final String iconName;

    private Icon(String iconName) {
        this.iconName = iconName;
    }

    public String getIconName() {
        return iconName;
    }

}
